### ISSUE TITLE
nginx error日志报错

### ISSUE THREAD

**Issue by knowyi** [nacos-group/nginx-nacos-upstream#14]
操作系统 ubuntu 20.04
nginx版本 1.20.2
nginx error日志里 一直会有报错信息，100个并发压测一个静态接口 大概会有0.5%的请求失败
![image](https://github.com/user-attachments/assets/a48e3a6a-e746-440d-9449-9aba3d8a5119)

这个是我nacos 配置
user  root;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

nacos {
    server_list 172.17.0.6:8848; # nacos 服务器列表，空格隔开

    # 可以使用 grpc 订阅。 nacos 2.x 版本才支持，推荐使用。
    grpc_server_list 172.17.0.6:9848; # nacos grpc服务器列表，空格隔开。一般是 nacos 端口 + 1000
    username "XXX";
    password "XXXX";
    service_namespace "8253480f-782f-43d4-9d05-f80ee6b7e4fb";
    error_log logs/nacos.log info;
    #default_group DEFAULT_GROUP; # 默认的nacos group name
  cache_dir nacos_cache/;
}

**Comment by knowyi** [comment]
持续压了1个小时 发现cpu 100% nginx挂了

**Comment by zhwaaaaaa** [comment]
http {} 中的配置可以提供一下吗

**Comment by knowyi** [comment]
配置就是默认配置 开启了gzip 添加了 include /etc/nginx/conf.d/*.conf; 具体的配置都单独在conf.d目录下单独写了  http {
    include       mime.types;
    default_type  application/octet-stream;

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    gzip  on;
 
    include /etc/nginx/conf.d/*.conf;
}

**Comment by knowyi** [comment]
这个是 conf.d 下的配置文件 

upstream drivermgmt-api {
    # 不需要写死 后端 ip。配置 nacos 服务名，nginx 自己订阅
    nacos_subscribe_service service_name=drivermgmt-api group=drivermgmt;
}

upstream pos-admin {
    # 不需要写死 后端 ip。配置 nacos 服务名，nginx 自己订阅
    nacos_subscribe_service service_name=pos-admin-api group=pos;
}

upstream pos-exchange {
    # 不需要写死 后端 ip。配置 nacos 服务名，nginx 自己订阅
    nacos_subscribe_service service_name=pos-exchange-api group=pos;
}


server {
    listen 80;
    server_name localhost;

    client_max_body_size 200M;

    proxy_connect_timeout       300;
    proxy_send_timeout          300;
    proxy_read_timeout          300;
    send_timeout                300;

    location /pos-admin-api/ {
        proxy_pass http://pos-admin/pos-admin-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /pos-exchange-api/ {
        proxy_pass http://pos-exchange/pos-exchange-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /dms-api/ {
        proxy_pass http://drivermgmt-api/dms-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

**Comment by knowyi** [comment]
我找时间测试一下，年底比较忙 没有在测试
